// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnkuindvpsqhrwnkfnyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ua3VpbmR2cHNxaHJ3bmtmbnlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTg0NTMsImV4cCI6MjA2MTczNDQ1M30.JdLlHOpu0A9o72F4vp4bNa3H_vu7x271NjGKGTcNfKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);